# Generated by Django 3.2.9 on 2021-11-27 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('father', models.CharField(max_length=250)),
                ('dataofbirth', models.DateTimeField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=45)),
                ('pin', models.CharField(max_length=6)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('marks', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
