# Generated by Django 3.2.9 on 2021-11-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_dataofbirth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='students',
            old_name='dataofbirth',
            new_name='dateofbirth',
        ),
    ]
