# Generated by Django 3.2.9 on 2021-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211127_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
