# Generated by Django 3.2.9 on 2021-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_students_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='store',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
