# Generated by Django 3.2.9 on 2021-11-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='store',
        ),
    ]
